new problem
turns out the previous probelm i gave now has to do with the colour cells method, however i somehow fixed it and now we are back to the error in the if statement in game loop:
    if p1.incell(gridlist).getcoords()==taskcells[i].getcoords():
                                        ~~~~~~~~~^^^
TypeError: 'Cell' object is not subscriptable