the error changed
i switched .pop to remove as i thougth maybe the error was because its now a stack. this caused this error instead:
    taskcells=taskcells.remove(0)
              ^^^^^^^^^^^^^^^^^^^
ValueError: list.remove(x): x not in list